name: release

on:
  workflow_call: {}

permissions:
  contents: write
  packages: write
  issues: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Zig Compiler
        uses: mlugg/setup-zig@v1.2.2
      - name: cosign-installer
        uses: sigstore/cosign-installer@v3.8.2
      - name: Anchore SBOM Action
        uses: anchore/sbom-action/download-syft@v0.19.0
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install macOS SDKs
        shell: bash
        env:
          MACOS_SDK_URL: ${{ secrets.MACOS_SDK_URL }}
        run: |
          curl -L "$MACOS_SDK_URL" | tar -J -x -C /opt
      - uses: goreleaser/goreleaser-action@v6.3.0
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          SDKROOT: /opt/MacOSX11.3.sdk
          GITHUB_REPOSITORY_URL: "${{github.server_url}}/${{github.repository}}"
          GITHUB_REPOSITORY: ${{github.repository}}