name: version-bump
on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch: {}

jobs:
  version-bump:
    permissions:
      contents: write
    if: ${{ github.event.pull_request.merged || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install cargo-bump
        run: cargo install cargo-bump
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: 'true'
      - name: Bump version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          cargo bump patch --git-tag          
          git push origin main --tags
